再帰を利用しないように修正
amanoese/yukichant pull request #33
Opened 2022-07-02 06:02 UTC by frodo821

再帰を利用しないように修正することで、入力文字列の長さに制限のないように修正しました

this will fixes #31.

2022-07-04 13:16 UTC, amanoese reviewed
PRありがとうございます。
素晴らしい修正でマージしたいのですが、
もし可能であれば下記２点について対応していただけると幸いです。

1. PRの内容と関係のない修正(セミコロンの付与)の削除
2. エラーが起きるケースのテストコードの追加

2022-07-04 13:16 UTC, amanoese commented on src/machine-encrypt.js
上記セミコロンを付与している対応について、今回のPR内容に本質的には関係がなく、
Git Blameなどをした際にコメントが分かりづらくなるためセミコロンを削除していただけると幸いです。

2022-07-04 13:16 UTC, amanoese commented on src/machine-encrypt.js
> +};
上記セミコロンを付与している対応について、今回のPR内容に本質的には関係がなく、
Git Blameなどをした際にコメントが分かりづらくなるため削除していただけると幸いです。

2022-07-04 13:17 UTC, amanoese requested changes

2022-07-04 13:17 UTC, amanoese commented on src/machine-encrypt.js
上記セミコロンを付与している対応について、今回のPR内容に本質的には関係がなく、
Git Blameなどをした際にコメントが分かりづらくなるため削除していただけると幸いです。

2022-07-07 11:54 UTC, frodo821 commented
> PRありがとうございます。 素晴らしい修正でマージしたいのですが、 もし可能であれば下記２点について対応していただけると幸いです。
> 
> 1. PRの内容と関係のない修正(セミコロンの付与)の削除
> 2. エラーが起きるケースのテストコードの追加

対応しました～

2022-07-09 03:15 UTC, amanoese approved these changes

2022-07-09 03:17 UTC, amanoese commented
@frodo821 テストケースの追加ありがとうございました。
PRありがとうございます。

2022-07-09 03:17 UTC, merged